### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/recursive-minisite#76]
- [x] clarify sidebar checkout
- [x] make new download on github, remove `beta` tags
- [x] add direct download link to site
- [x] add "checkout" CTA section above character grid
